FROM centos:7.2.1511

ENV JAVA_RELEASE jdk1.8.0_162

ENV JAVA_PACK_NAME jdk-8u162-linux-x64

ENV JAVA_HOME /usr/local/$JAVA_RELEASE

ENV PATH $JAVA_HOME/bin:$PATH

ENV LANG en_US.UTF-8

COPY $JAVA_PACK_NAME.tar.gz /tmp/
RUN cd /tmp/ ; \
	tar -xf $JAVA_PACK_NAME.tar.gz -C /usr/local ; \ 
	rm $JAVA_PACK_NAME.tar.gz ; \
	java -version
